baseurl = "https://www.filipesilvestre.com/"
# baseurl = "/"
languageCode = "en-us"
title = "Filipe's Website"
pygmentsUseClasses = true
pluralizelisttitles = false
googleAnalytics = "UA-69996700-1"
enableRobotsTXT = true
disqusShortname = "filipesilvestre"

[permalinks]
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[Params]
  description = "Filipes's Website"
  author = "Filipe Silvestre"
  employer = "Telesign"
  current_city = "Los Angeles, CA"
  bio_top = "I am a design-minded, detail oriented software engineer who is passionate about building great applications. I'm particularly interested in Machine Learning and Data Science."
  bio_bottom = "I love dogs, podcasts, punk rock, hip-hop, and adventure. I often think about technology, social issues, and the environment."
  authorDescription = "Filipe Silvestre is a software engineer based in Los Angeles who builds quality Android apps and backend services."
  siteDescriptors = ["blog", "dogs", "android", "software", "engineering", "software engineer", "python", "los angeles,", "outdoors", "adventure", "programming", "software", "Filipe Silvestre", "Silvestre", "Filipe"]
  authorTwitter = "filuminati90"
  authorGithub = "fsilvestre90"
  authorLinkedin = "silvestrefilipe"
  authorInstagram = "filuminati90"
  coverImage = "/images/avatar.png"
  authorSignature = "fs."
  resume = "/files/Filipe_Silvestre_Resume.pdf"
  email = "fssilvestre5@gmail.com"
  nocomment = true

## Main Menu
[[menu.main]]
  name = "about"
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "portfolio"
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "blog"
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  url = "/resume/"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
